[general]
iface_name = dwc00

phc_device = /dev/ptp0

shm_name = /score_time_vehicle_time
shm_size = 4096

#   0 = kPublishOnly
#   1 = kDisciplineSystemClock
abs_mode = 0


[ntp]
ntp_servers = pool.ntp.org

ntp_port = 123

ntp_query_interval_ms = 1000

ntp_request_timeout_ms = 250

ntp_samples_to_lock = 3

ntp_offset_ewma_alpha = 0.2
ntp_jitter_ewma_alpha = 0.2


[abs]
abs_publish_interval_ms = 200

abs_external_enable = 0

abs_source_socket = /run/score_time/abs_time_source.sock

abs_source_timeout_ms = 5000


[pdelay]
pdelay_req_interval_ms = 1000

pdelay_timeout_ms = 1000


[sync]
sync_timeout_ms = 1000


[threshold]
unstable_offset_threshold_ns = 10000

jump_future_threshold_ns = 600000000
